### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [LihaLiha/c202309#4]
### 없는 파일
- challenge/week3/do-while_even.c
- challenge/week3/while_even.c
- challenge/week4/pyramidReverse.c
- challenge/week5/functionMulti.c
- practice/week4/pyramid.c
- practice/week5/functionHap.c
- practice/week7/7_travel.c
- project/week8/todo_manager.c
    - 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week6/studentGrade
    - Error: void function 'printRanks' should not return a value [line 64]
       - 해당 함수에 반환형이 void인데 return으로 값을 반환하는 문제가 있습니다.  반환형을 맞춰주세요.

**Comment by LihaLiha** [comment]
없는 파일 커밋 했습니다.
이름 다른 파일들 수정했습니다.
studentGrade 오류 수정했습니다.
